<a href="https://colab.research.google.com/github/rajlm10/ZBC_ML_Workshop/blob/main/sklearn_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('/content/50_Startups.csv')

In [3]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
X=data.iloc[:,:-1].values
print(X.shape)
y=data.iloc[:,-1].values.reshape(X.shape[0],1)
print(y.shape)

(50, 4)
(50, 1)


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [9]:
X_train

array([[93863.75, 127320.38, 249839.44, 'Florida'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [44069.95, 51283.14, 197029.42, 'California'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [27892.92, 84710.77, 164470.71, 'Florida'],
       [1315.46, 115816.21, 297114.46, 'Florida'],
       [0.0, 135426.92, 0.0, 'California'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [77044.01, 99281.34, 140574.81, 'New York'],
       [46426.07, 157693.92, 210797.67, 'California'],
       [61136.38, 152701.92, 88218.23, 'New York'],
       [165349.2, 136897.8, 471784.1, 'New York'],
       [22177.74, 154806.14, 28334.72, 'California'],
       [72107.6, 127864.55, 353183.81, 'New York'],
       [55493.95, 103057.49, 214634.81, 'Florida'],

In [14]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False, handle_unknown='ignore')
train_enc = ohe.fit_transform(X_train[:,3].reshape(X_train.shape[0],1))
#Converting back to a dataframe 
pd.DataFrame(train_enc, columns=ohe.get_feature_names())

x0_California  x0_Florida  x0_New York
0             0.0         1.0          0.0
1             0.0         1.0          0.0
2             1.0         0.0          0.0
3             0.0         0.0          1.0
4             0.0         0.0          1.0
5             1.0         0.0          0.0
6             0.0         1.0          0.0
7             0.0         1.0          0.0
8             1.0         0.0          0.0
9             0.0         0.0          1.0
10            1.0         0.0          0.0
11            1.0         0.0          0.0
12            0.0         0.0          1.0
13            1.0         0.0          0.0
14            0.0         0.0          1.0
15            0.0         0.0          1.0
16            1.0         0.0          0.0
17            0.0         0.0          1.0
18            0.0         1.0          0.0
19            0.0         0.0          1.0
20            0.0         0.0          1.0
21            1.0         0.0          0.0
22            0.0         1.0          0.0
23            1.0         0.0          0.0
24            0.0         0.0          1.0
25            0.0         1.0          0.0
26            0.0         0.0          1.0
27            0.0         0.0          1.0
28            0.0         1.0          0.0
29            1.0         0.0          0.0
30            0.0         1.0          0.0
31            0.0         1.0          0.0
32            0.0         1.0          0.0
33            1.0         0.0          0.0
34            1.0         0.0          0.0
35            0.0         1.0          0.0
36            1.0         0.0          0.0
37            0.0         1.0          0.0
38            0.0         1.0          0.0
39            0.0         0.0          1.0

In [18]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False,drop='first')
train_enc = ohe.fit_transform(X_train[:,3].reshape(X_train.shape[0],1))
#Converting back to a dataframe 
pd.DataFrame(train_enc, columns=ohe.get_feature_names())

x0_Florida  x0_New York
0          1.0          0.0
1          1.0          0.0
2          0.0          0.0
3          0.0          1.0
4          0.0          1.0
5          0.0          0.0
6          1.0          0.0
7          1.0          0.0
8          0.0          0.0
9          0.0          1.0
10         0.0          0.0
11         0.0          0.0
12         0.0          1.0
13         0.0          0.0
14         0.0          1.0
15         0.0          1.0
16         0.0          0.0
17         0.0          1.0
18         1.0          0.0
19         0.0          1.0
20         0.0          1.0
21         0.0          0.0
22         1.0          0.0
23         0.0          0.0
24         0.0          1.0
25         1.0          0.0
26         0.0          1.0
27         0.0          1.0
28         1.0          0.0
29         0.0          0.0
30         1.0          0.0
31         1.0          0.0
32         1.0          0.0
33         0.0          0.0
34         0.0          0.0
35         1.0          0.0
36         0.0          0.0
37         1.0          0.0
38         1.0          0.0
39         0.0          1.0

In [19]:
ohe.transform(X_test[:,3].reshape(X_test.shape[0],1))

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.]])

In [23]:
temp=['California','Florida','Florida']

In [21]:
np.array(temp).shape

(3,)

In [24]:
ohe.transform(np.array(temp).reshape(np.array(temp).shape[0],1))

array([[0., 0.],
       [1., 0.],
       [1., 0.]])

In [29]:
X_train=np.hstack((X_train[:,:-1],train_enc))
X_train

array([[93863.75, 127320.38, 249839.44, 1.0, 0.0],
       [142107.34, 91391.77, 366168.42, 1.0, 0.0],
       [44069.95, 51283.14, 197029.42, 0.0, 0.0],
       [120542.52, 148718.95, 311613.29, 0.0, 1.0],
       [144372.41, 118671.85, 383199.62, 0.0, 1.0],
       [134615.46, 147198.87, 127716.82, 0.0, 0.0],
       [27892.92, 84710.77, 164470.71, 1.0, 0.0],
       [1315.46, 115816.21, 297114.46, 1.0, 0.0],
       [0.0, 135426.92, 0.0, 0.0, 0.0],
       [114523.61, 122616.84, 261776.23, 0.0, 1.0],
       [123334.88, 108679.17, 304981.62, 0.0, 0.0],
       [78013.11, 121597.55, 264346.06, 0.0, 0.0],
       [77044.01, 99281.34, 140574.81, 0.0, 1.0],
       [46426.07, 157693.92, 210797.67, 0.0, 0.0],
       [61136.38, 152701.92, 88218.23, 0.0, 1.0],
       [165349.2, 136897.8, 471784.1, 0.0, 1.0],
       [22177.74, 154806.14, 28334.72, 0.0, 0.0],
       [72107.6, 127864.55, 353183.81, 0.0, 1.0],
       [55493.95, 103057.49, 214634.81, 1.0, 0.0],
       [131876.9, 99814.71, 362861.36, 0.0, 1.

In [30]:
X_train.shape

(40, 5)

In [31]:
test_enc=ohe.transform(X_test[:,3].reshape(X_test.shape[0],1))
X_test=np.hstack((X_test[:,:-1],test_enc))
X_test.shape

(10, 5)

In [32]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

In [33]:
X_train

array([[ 0.34202149,  0.22787678,  0.12425038,  1.36277029, -0.69388867],
       [ 1.36207849, -1.0974737 ,  1.14990688,  1.36277029, -0.69388867],
       [-0.71081297, -2.5770186 , -0.34136825, -0.73379939, -0.69388867],
       [ 0.90611438,  1.0172367 ,  0.66890185, -0.73379939,  1.44115338],
       [ 1.40997088, -0.09115403,  1.30006861, -0.73379939,  1.44115338],
       [ 1.20367103,  0.96116332, -0.95248784, -0.73379939, -0.69388867],
       [-1.05285826, -1.34392538, -0.62843389,  1.36277029, -0.69388867],
       [-1.61480906, -0.19649414,  0.54106768,  1.36277029, -0.69388867],
       [-1.642623  ,  0.52691442, -2.07854935, -0.73379939, -0.69388867],
       [ 0.77885123,  0.05437051,  0.2294954 , -0.73379939,  1.44115338],
       [ 0.96515572, -0.45976843,  0.61043134, -0.73379939, -0.69388867],
       [ 0.00687736,  0.01677049,  0.25215324, -0.73379939, -0.69388867],
       [-0.01361318, -0.80643974, -0.83912073, -0.73379939,  1.44115338],
       [-0.66099544,  1.34830937, -0.2

In [34]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
y_pred = regressor.predict(X_test)

In [37]:
sc_y.inverse_transform(y_pred)

array([[126362.87908252],
       [ 84608.45383643],
       [ 99677.49425155],
       [ 46357.46068582],
       [128750.48288497],
       [ 50912.41741905],
       [109741.350327  ],
       [100643.24281644],
       [ 97599.275746  ],
       [113097.42524437]])

In [38]:
y_test

array([[134307.35],
       [ 81005.76],
       [ 99937.59],
       [ 64926.08],
       [125370.37],
       [ 35673.41],
       [105733.54],
       [107404.34],
       [ 97427.84],
       [122776.86]])

In [43]:
from sklearn.metrics import r2_score,mean_squared_error
print(mean_squared_error(y_test,sc_y.inverse_transform(y_pred)))
r2_score(y_test,sc_y.inverse_transform(y_pred))

82010363.04501359


0.8987266414319838