<a href="https://colab.research.google.com/github/rajlm10/ZBC_ML_Workshop/blob/main/ZBC_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Basics

Numpy is a very fast library that is useful for machine learning. It incorporates various linear algebra functions and can perform large-scale mathematical manipulations

#Best numpy guide I've ever seen

https://towardsdatascience.com/the-ultimate-beginners-guide-to-numpy-f5a2f99aef54

#Numpy Array 

In [57]:
import numpy as np

a=[[1,2],[3,4],[5,6]] #Create an np array
a=np.array(a)

print(a)
print()
a.shape


[[1 2]
 [3 4]
 [5 6]]



(3, 2)

In [14]:
print(np.mean(a,axis=0)) #Axis 0 refers to a.shape[0]
print(np.mean(a,axis=1)) #Axis 1 refers to a.shape[1]



[3. 4.]
[1.5 3.5 5.5]


In [58]:
a[0]

array([1, 2])

In [60]:
a[0][1]

2

In [61]:
a[:2,:]

array([[1, 2],
       [3, 4]])

In [15]:
a.reshape((1,6)) #Reshape an array 

array([[1, 2, 3, 4, 5, 6]])

In [17]:
np.linalg.norm(a) #Root of sum of squares of all numbers 

9.539392014169456

In [18]:
np.linalg.norm(np.array([3,4])-np.array([0,0])) #Dist between two arrays

5.0

In [25]:
print(np.sqrt(169))
np.exp(5)
#np.log

13.0


148.4131591025766

#Matrices

In [21]:
matrix1=np.random.randint(1,10,(4,3))
matrix2=np.random.randint(1,10,(3,4))
print(matrix1)
print()
print(matrix2)

[[1 6 2]
 [8 4 3]
 [8 1 9]
 [5 7 2]]

[[1 2 4 4]
 [3 6 3 9]
 [3 1 7 1]]


In [22]:
matrix1@matrix2 #Matrix multiplication

array([[25, 40, 36, 60],
       [29, 43, 65, 71],
       [38, 31, 98, 50],
       [32, 54, 55, 85]])

In [28]:
matrix1+matrix2.T #Transpose

array([[ 2,  9,  5],
       [10, 10,  4],
       [12,  4, 16],
       [ 9, 16,  3]])

In [43]:
matrix1*matrix2.T #Element wise multiplication

array([[ 1, 18,  6],
       [16, 24,  3],
       [32,  3, 63],
       [20, 63,  2]])

In [27]:
np.linalg.pinv(matrix1) #Pseudo-inverse, works with non square matrices

array([[-0.12607254,  0.15476897, -0.02885002,  0.0237442 ],
       [ 0.10977522, -0.0246499 , -0.03113281,  0.0672973 ],
       [ 0.10669795, -0.12812758,  0.13856168, -0.03803415]])

In [31]:
#np.linalg.det() determinant
#np.abs() absolute
np.cov(matrix1) #Covariance matrix

array([[  7.        ,  -3.5       , -11.        ,   4.5       ],
       [ -3.5       ,   7.        ,   2.5       ,   2.        ],
       [-11.        ,   2.5       ,  19.        ,  -9.5       ],
       [  4.5       ,   2.        ,  -9.5       ,   6.33333333]])

#Broadcasting


In [37]:
a=np.array([[1,2,3],[4,5,6]])
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [40]:
a+[9,8,7]

array([[10, 10, 10],
       [13, 13, 13]])

In [41]:
a+np.array([[9],[8]])

array([[10, 11, 12],
       [12, 13, 14]])

#Boolean logic

In [44]:
a>5

array([[False, False, False],
       [False, False,  True]])

In [47]:
np.logical_and(a>5,a==5)

array([[False, False, False],
       [False, False, False]])

In [48]:
np.logical_or(a>5,a==5)

array([[False, False, False],
       [False,  True,  True]])

#Q. Generate random numbers between 1 and 10 of size (4,4) and print the sum of all numbers greater than 5 in a single line of code without using if conditions

In [51]:
a=np.random.randint(1,10,(4,4))
a

array([[5, 9, 3, 3],
       [5, 6, 6, 2],
       [9, 3, 4, 3],
       [2, 7, 4, 3]])

In [52]:
np.sum((a>5)*a)

37

In [53]:
index=np.array([1,2,3,4,5])
prices=np.array([100,20,13,54,65])

#cheat-sort

In [55]:
index[np.argsort(prices)] 

array([3, 2, 4, 5, 1])